### ISSUE TITLE
stream not found

### ISSUE THREAD

**Issue by tekumara** [ConnectEverything/nats-by-example#132]
https://natsbyexample.com/examples/jetstream/limits-stream/python#output
```
[1A[1B[0G[?25l[+] Creating 2/0
 [32m✔[0m Network 263e8d57_default   [32mCreated[0m[34m0.1s [0m
 [32m✔[0m Container 263e8d57-nats-1  [32mCreated[0m[34m0.0s [0m
[?25h[1A[1B[0G[?25l[+] Running 0/0

[?25h[1A[1A[0G[?25l[34m[+] Running 1/1[0m
 [32m✔[0m Container 263e8d57-nats-1  [32mStarted[0m[34m0.3s [0m
[?25hTraceback (most recent call last):
  File "//main.py", line 74, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "//main.py", line 22, in main
    await js.delete_stream('events')
  File "/usr/local/lib/python3.10/site-packages/nats/js/manager.py", line 120, in delete_stream
    resp = await self._api_request(
  File "/usr/local/lib/python3.10/site-packages/nats/js/manager.py", line 362, in _api_request
    raise APIError.from_error(resp['error'])
  File "/usr/local/lib/python3.10/site-packages/nats/js/errors.py", line 84, in from_error
    raise NotFoundError(**err)
nats.js.errors.NotFoundError: nats: NotFoundError: code=404 err_code=10059 description='stream not found'
exit status 1
```

**Comment by bruth** [comment]
Thanks for the report, I will check it out.
